### ISSUE TITLE
Replace os with pathlib in the entire project

### ISSUE THREAD

**Issue by gosia-malgosia** [idealo/imageatm#19]
For now not all elements of the project use pathlib.

**Comment by gosia-malgosia** [comment]
This issue required adding an extra lib to setup.py (and mypy.ini)

NOTE: The currently used keras version does not allow loading/saving models using a pathlib objects. For now the pathlib Paths in the keras-related code were converted to string. If possible in the future they should be kept as Paths

**Comment by clennan** [comment]
Here is the related PR that got merged post Keras 2.2.4 https://github.com/keras-team/keras/pull/11466
We are currently using Keras 2.2.4, which is the latest version on PyPI. This should be fixed in TF 2.0 and using tf.keras.
